{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 140,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from tkinter import Canvas, Label, Tk, Frame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 141,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "# reload module\n",
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "from calculations import Calculations\n",
    "from point import Point\n",
    "from cursor_manager import CursorManager"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 142,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python310\\lib\\tkinter\\__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\grayni\\AppData\\Local\\Temp\\ipykernel_16264\\1526301546.py\", line 80, in on_enter\n",
      "    self.delete_cursor(event)\n",
      "TypeError: CursorManager.delete_cursor() takes 1 positional argument but 2 were given\n"
     ]
    }
   ],
   "source": [
    "root = Tk()\n",
    "\n",
    "canvas = CurveGrid(root, width=600, height=650, bg=\"#333333\")\n",
    "canvas.pack(expand=True, fill=\"both\")\n",
    "canvas.configure(bg=\"#333333\")\n",
    "\n",
    "root.title(\"сurves\")\n",
    "root.mainloop()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 143,
   "outputs": [],
   "source": [
    "class CurveGrid(Canvas, Frame, Calculations, Point, CursorManager):\n",
    "\n",
    "    def __init__(self, master=None, **kwargs):\n",
    "        super().__init__(master, **kwargs)\n",
    "        CursorManager.__init__(self)\n",
    "        self.root = master\n",
    "        # hover\n",
    "        self.bind(\"<Motion>\", self.on_enter)\n",
    "        # (optional: keyboard + ) LBM\n",
    "        self.bind(\"<Button-1>\", self.left_click)\n",
    "        # click and hold\n",
    "        self.bind(\"<B1-Motion>\", self.on_drag)\n",
    "        # left mouse button release\n",
    "        self.bind(\"<ButtonRelease-1>\", self.on_release)\n",
    "        self.ctrl_pressed = False\n",
    "        self.root.bind(\"<KeyPress>\", self.ctrl_ready)\n",
    "        self.bind('<Control-KeyRelease>', self.arrow_cursor)\n",
    "\n",
    "\n",
    "        self.selected_index = None\n",
    "        self.lim = {\n",
    "            'x': 8,\n",
    "            'y': 63,\n",
    "            'dist_remove': 6\n",
    "        }\n",
    "        self.x = self.y = 0\n",
    "        self.start_x = self.end_y = 50\n",
    "        self.end_x = self.start_y = 560\n",
    "        self.start_point = (self.start_x, self.start_y)\n",
    "        self.end_point = (self.end_x, self.end_y)\n",
    "\n",
    "        self.points = [self.start_point, self.start_point, (150, 200), (250, 100), self.end_point, self.end_point]\n",
    "        self.curve_points = None\n",
    "\n",
    "        # create Label coords,\n",
    "        self.label = Label( master, text=f\"x: 0\\ny: 0\", anchor=\"w\", justify=\"left\", bg=\"#333333\", fg=\"#aaaaaa\", font=(\"Arial\", 14))\n",
    "        self.label.place(x=50, y=580)\n",
    "\n",
    "        # init grid & line\n",
    "        self.draw_grid()\n",
    "        self.draw_line()\n",
    "\n",
    "    def on_key_release(self, event):\n",
    "        if event.keysym == 'Control_L' or event.keysym == 'Control_R':\n",
    "            self.ctrl_pressed = False\n",
    "            print(\"Клавиша Ctrl отпущена\")\n",
    "\n",
    "    def draw_grid(self):\n",
    "        # vertical lines\n",
    "        for x in range(50, 561, 102):\n",
    "            self.create_line(x, 50, x, 561, fill=\"#444444\")\n",
    "\n",
    "        # horizontal lines,\n",
    "        for y in range(50, 561, 102):\n",
    "            self.create_line(50, y, 561, y, fill=\"#444444\")\n",
    "\n",
    "    def draw_line(self):\n",
    "        self.delete(\"curve\", \"point\")\n",
    "\n",
    "        # curve coords\n",
    "        self.curve_points = self.curve_coords(self.points[1:-1])\n",
    "\n",
    "        # curve\n",
    "        self.create_line(\n",
    "            # left fix point, curve points, right fix point\n",
    "            self.points[0], *self.curve_points, self.points[-1],\n",
    "            fill=\"#ffffbb\",\n",
    "            width=1,\n",
    "            tags=\"curve\"\n",
    "        )\n",
    "\n",
    "        # points\n",
    "        for i, (x, y) in enumerate(self.points, start=0):\n",
    "            if i not in (0, len(self.points)-1):\n",
    "                self.draw_point(x, y) # class Point\n",
    "\n",
    "    def on_enter(self, event):\n",
    "        # hover points\n",
    "        if event.state & 0x4:\n",
    "            self.delete_cursor(event)\n",
    "        if self.allow_add_point(event):\n",
    "            self.hand_cursor(event) if self.allow_influence_point(event) else self.cross_cursor(event)\n",
    "        else:\n",
    "            if self.allow_influence_point(event):\n",
    "                if event.state & 0x4:\n",
    "                    self.delete_cursor(event)\n",
    "                else:\n",
    "                    self.hand_cursor(event)\n",
    "            else:\n",
    "                self.arrow_cursor(event)\n",
    "\n",
    "    def left_click(self, event):\n",
    "        self.x, self.y = event.x, event.y\n",
    "\n",
    "        # ctrl + LMB\n",
    "        if event.state & 0x4:\n",
    "            if self.allow_influence_point(event):\n",
    "                self.remove_point()\n",
    "                self.draw_line()\n",
    "        else:\n",
    "            # add a point to the curve & redraw the curve\n",
    "            if self.allow_add_point(event):\n",
    "                self.add_point(self.x, self.y)\n",
    "                self.draw_line()\n",
    "\n",
    "            # choose the nearest point\n",
    "            self.choose_point(self.x, self.y)\n",
    "\n",
    "    # drag point,\n",
    "    def on_drag(self, event):\n",
    "        self.configure(cursor=self.drag_path)\n",
    "        # event.widget.configure(cursor=\"fleur\")\n",
    "        # restricted movement coordinates\n",
    "        self.x = max(self.start_x, min(event.x, self.end_x))\n",
    "        self.y = max(self.end_y, min(event.y, self.start_y))\n",
    "\n",
    "        # selected point\n",
    "        self.points[self.selected_index] = (self.x, self.y)\n",
    "\n",
    "        # coord: x -> next point, previous point\n",
    "        prev_x, _ = self.points[self.selected_index - 1]\n",
    "        next_x, _ = self.points[self.selected_index + 1]\n",
    "\n",
    "        # limit min distance between points\n",
    "        if self.selected_index != 1 and self.x - prev_x < self.lim['x']:\n",
    "            self.limited_point(prev_x + self.lim['x'])\n",
    "        elif self.selected_index != len(self.points)-2 and next_x - self.x < self.lim['x']:\n",
    "            self.limited_point(next_x - self.lim['x'])\n",
    "\n",
    "        self.label.config(text=f\"x: {round((self.x - 50) / 2)}\\ny: {round((560 - self.y) / 2)}\")\n",
    "\n",
    "        # boundary invisible points\n",
    "        if self.selected_index == 1:\n",
    "            self.points[0] = (self.start_x, self.y)\n",
    "        elif self.selected_index == len(self.points) - 2:\n",
    "            self.points[-1] = (self.end_x, self.y)\n",
    "\n",
    "        self.draw_line()\n",
    "\n",
    "    def on_release(self, event):\n",
    "        self.selected_index = None\n",
    "        self.arrow_cursor(event)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 144,
   "outputs": [],
   "source": [
    "# points = [(50, 560), (150, 200), (250, 100), (560, 50)]"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 145,
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "\n",
    "class MyApp:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.ctrl_pressed = False\n",
    "        self.root.bind(\"<KeyPress>\", self.on_key_press)\n",
    "        self.root.bind(\"<KeyRelease>\", self.on_key_release)\n",
    "\n",
    "    def on_key_press(self, event):\n",
    "        if event.keysym == 'Control_L' or event.keysym == 'Control_R':\n",
    "            self.ctrl_pressed = True\n",
    "            print(\"Клавиша Ctrl нажата\")\n",
    "\n",
    "    def on_key_release(self, event):\n",
    "        if event.keysym == 'Control_L' or event.keysym == 'Control_R':\n",
    "            self.ctrl_pressed = False\n",
    "            print(\"Клавиша Ctrl отпущена\")\n",
    "\n",
    "root = tk.Tk()\n",
    "app = MyApp(root)\n",
    "root.mainloop()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 145,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}